### ISSUE TITLE
Dark mode isn't supported

### ISSUE THREAD

**Issue by millionsofplayers** [thayerw/lemmy-rediggit#1]
[Video](https://files.catbox.moe/42dz6s.mp4)

Also can you add an option to completely remove rounded corners? I updated the style and more corners are rounded than before.

**Comment by thayerw** [comment]
I'm leaving the corners rounded for now (working on a few different concepts), but you can easily disable most rounded corners by adding the following line:

```
/* remove rounded corners everywhere */
.rounded, .card, .alert, .badge, .btn { border-radius: 0 !important; }
```

The platform itself is under rapid development, and the front-end HTML/CSS is changing significantly even between version bumps (0.18 to 0.18.1 saw big changes). I'm hoping to contribute to the official project soon, to increase the uniqueness of elements and in turn allow users to style specific components more reliably.
